
## Filtros / Seleção em dataframe

In [0]:
import pandas as pd

In [12]:
copacabana = pd.read_csv('copacabana.csv', delimiter=';') #A separacao das colunas para esse arquivo é feita por ;, por isso o delimiter
copacabana.columns #Exibe todas as colunas

Index(['Posicao', 'Quartos', 'Vagas', 'DistIpanema', 'DistPraia', 'DistFavela',
       'RendaMedia', 'RendaMovel', 'RendaMovelRua', 'Vu2009', 'Mes', 'Idade',
       'Tipologia', 'AreaConstruida', 'VAL_UNIT', 'X', 'Y'],
      dtype='object')

In [13]:
copacabana['Quartos'].describe() #Descreve estatisticamente os dados dessa coluna

count    1675.000000
mean        1.767510
std         1.142523
min         0.010000
25%         1.000000
50%         2.000000
75%         3.000000
max         6.000000
Name: Quartos, dtype: float64

In [14]:
copacabana.loc[copacabana['Quartos'] == 5] #Função para retornar todos os elementos dentro da condição idicada para a coluna escolhida

      Posicao  Quartos  Vagas  ...  VAL_UNIT            X           Y
173         1      5.0   0.01  ...      6316  686522.9800  7458989.87
1521        1      5.0   3.00  ...      5000  686965.3201  7459109.71

[2 rows x 17 columns]